language: python
sudo: required
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -r dev-requirements.txt
- pip install -e .
- pip install coveralls==1.3.0
- pip list
script:
- travis_wait py.test tests --cov rasa_core_sdk --pep8 -v
after_success:
- coveralls
jobs:
  include:
  - stage: deploy
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: amn41
      distributions: "sdist bdist_wheel"
      on:
        branch: master
        tags: true
      password:
        secure: "mOpBnifHsrqQdfJVeU2yF7EcuMRHZz7TLA7N6WTZSDbBPVWKMxPt75lqNkMei/5DAMSRspUztdN8wA7/Xw4bVeshTZvlRc5BESLrViPR8/Kc8tqcKYCJLDXZhoKNkukN5c/JnPhO0d0sKRc65VZaxyi92nQmuc9xYh5cLvMaKB6vYMAvXZvcEpDFW4A6BlFSB4dfHbxAlO3ZAc+PRg1UBTxdaEBCV2JK3+qXyRygJ+ILUp2ZDSWgdeitQn4K4WQ5vA8bqeWOLACrDAoki+ozWdnFQJ/AZZCI8mrL5MtaU99ttCM3nvLdiyxmpWC8qHta59Gsc+4AY1M2QEQ6ZKj23wWxquZNYbe75THJ/xJ3tNFU9a/0rNQAk46Wc2Hj4x894mY+92kXQDBlO+AhwVqBpaZChtOwTZAtKjR/YLxfty2tNIZcp1ott+LHCV5vWhd8xEiiu18Dn4mQltCvzNSbro2cX4edDCj13FOolAs0KSKfTCLOYDtpjufOiGK9cP271T9krYM2Z9w4JXnfRNymFrooJRT51ilaCOvENxZN5GeBXgpPOXIU/YaxCt6A25ktSMeHjJb8WVJu8Z1jGCz3mJcBg7Y2ISATHLui0whygYLGEK6khb8Lnmh2eEWh0cij3kKGvtQR9zdEcy1C+zpckoLeQk/UPjsLgoUmVk+F6mg="
