language: python
sudo: required
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -r dev-requirements.txt
- pip install -e .
- pip install coveralls==1.3.0
- pip list
script:
- travis_wait py.test tests --cov rasa_core_sdk --pep8 -v
after_success:
- coveralls
jobs:
  include:
  - stage: deploy
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: amn41
      distributions: "sdist bdist_wheel"
      on:
        branch: master
        tags: true
      password:
        secure: "F+APzquUt2MwcfHLERNrgvzqyxHgOjWWTqu53zPBuXAk4fFfB0a6unoF1+rZchVwaXmJGTY0QPlCk9L+GPWy+Sxu5ythzlXMMUJaM+NVtu/Pmq+uDxAo2TQigNAEVNsoE0i8iS19wiyoqqQqzmmmSHD8Tkfts6zBhBKzAhWQxYOaJjir598khljOE0wljLIy3lKdYJ/M0D1lCGRIP20XYp9gN3wR4aaPgLlHgqgXQkUE+woU1Hotz3rC46ty2o8c0VQaWtdbeQArSjMi3d1Bb5W9EF3sRlz0h6ayPHHKxefNyyPFSnhGDpMbInQFkRz4VQ9FqfuTwRisUh1MSq3YFoYFeikmCKfhyun4kdtOld1uqvr5MBooC+atwRhIa2ScpjnyzS/HGPQ+SX63oiuHOMPr69UNBWZnbVZu8HJWlPVKXCBGoE8g7jhg7jqtImVs7jNuII3+w181BwQ2+L1F3rTtlYB/WnBLezUpf17JaP8dxsM4qGi4wM/fSz37k0PjWp2YHBq7sXLgGLe66SkT80R7Hth+6N7m1DSP5evHCOSiCIgdPDJE+nQyuPRaFHhMUEsTkZQJ7S7L9bd+z/5g17cvyM3S+BEXA3FH75q5cUpYmlAn8MZ7eyt1G6c2z2whjLaLYWyBLpZ5gM3tNxulXOb7M17puqXd5VtSBt9TFYI="
