language: python
sudo: required
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -r dev-requirements.txt
- pip install -e .
- pip install coveralls==1.3.0
- pip list
script:
- travis_wait py.test tests --cov rasa_core_sdk --pep8 -v
after_success:
- coveralls
jobs:
  include:
  - stage: deploy
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: amn41
      distributions: "sdist bdist_wheel"
      on:
        branch: master
        tags: true
      password:
        secure: "K/49/Aa3Ab9Nin6mJMTtMCGiOyS06j3q2/SKqxW+cCmsLw+gEQgp7umZ5fp12SEDTBqtOwH+y/P45Va9o+3LrM65uxinxpkedxJEUBLVGipJB9SXUlYk1ythagB++4CtGuYoZ0+QMyZiCP6vhD9zqY8k3LXL/V6cVKVNE1rGJ9cLLu1JEY6yEWmk06uZaNDxQYs3VAywjhmNWpGqQyVZXZx9sTbKqrGUkdtp9sOdaXy3cvzdKP23OWbLL93CrfmsNBJoy0ZL0ssqRMquEwVMxnXLuy+oAICkamcqnThCVUS9/ceesWTF00btHRuK+I4sFM/GJ7vFT5i0emzt5SbjXhlquPxaeV9NuhOP09hw7OsO5imr3tWGoVg5rO5CH2bNvLFnlRYuezUVYnqGBre6AHYX+njSsFqpPlaMpXLxuQSQVFYoVzpIxlOfdkqcgYLMY2vEqHgLWlKnOCYHwZrKJRK3qpOFSmn8t3zEFDpN/7lbKCoch/gd23sdANYqtxb/XDav6TyJGrcUcpunzagbGTyXvNUUB+og9UCEzUlCCUEQte/rfkz5KZzaMUhx91r281pPuwdZwaGXER/lkxiVWs+lzjAagQ+b7wYA3ktv3kHvND13HA/udvAguqHJa9BUp7kFrrt0fZQEf5TCL1WZjGzViDUMIQyN5573cLI8PFs="
