language: python
sudo: required
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -r dev-requirements.txt
- pip install -e .
- pip install coveralls==1.3.0
- pip list
script:
- travis_wait py.test tests --cov rasa_core_sdk --pep8 -v
after_success:
- coveralls
jobs:
  include:
  - stage: deploy
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: amn41
      distributions: "sdist bdist_wheel"
      on:
        branch: master
        tags: true
      password:
        secure: "LtilZCsCvhPCd+8Sqdd6gWwCfwow+ctmns0zQndK51m4iYs9okr8AdJnyME6v+fj6W2o1JonmJqOv3mkEs0eWop7kdVDcjWpaK0ApVqgbalzZ1f5h13CIXho65KOupIn4JwRoJZC3rGAavFVw5Xgva/ApnCtJCTmEhgIjmBX5cVLnFcM7I1IfMUeEcQhYIVE2yjC36MAlq4UgOCg3dWgXK6EggWojgWSQ1QhKXOulz998ICFtFfvHEFJSu8fRgQzNdsgXMZuJh+yAVke7HK/A+Gppi/JcOYumCh1hlQKbT7OOdd/nHaPpWMOKiv8sjAjR6hhb+SAU97rJQjNSA+8G6N+v+8L7axxYSscgCa4/2I2M/XeRzdIb5rwoxFjboI52uFqXDl2Tl9x4xTlscLQ72lz/V8NeThSsEQAgvLa5kFjNEYWeX4KM88ZGG4T0Jvzd6ZX9dv0P+qnVf1NI6q4vu1yHutii1QBRfK12X/UPhgYPEb2LyllC0Y7ARtCVtrZlw/1Nm8p9dKASNm6JLc0PaHS3QhihzfvKWb5nJN1DxvM2TMl78olukYsggdOVUIA3CNhqnYkPDYRJRYPqv/HnNFFso+XFSdQWEO/a3oVMq75wBlV0jBE7Lt0ZLZKD3dtQTIRTLb/NfIHToyezFAod68ngpHDEoQvmMxELHRw/Vk="
