language: python
sudo: required
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -r dev-requirements.txt
- pip install -e .
- pip install coveralls==1.3.0
- pip list
script:
- travis_wait py.test tests --cov rasa_core_sdk --pep8 -v
after_success:
- coveralls
jobs:
  include:
  - stage: deploy
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      user: amn41
      distributions: "sdist bdist_wheel"
      on:
        branch: master
        tags: true
      password:
        secure: "BqRvS/po0JwQGHB2HYCrQS07S+68mWBsY6q8Mmi5DqSpkI0UFdajbZUJcsu9PnJu446Uzm6nB/iIAh9KGv2Zq+0V+2w4Vwhcmt04fhwCltFq8Y4p/AD7v0d0LS/xS4iHmL1jG/kTktTcJ+YBtUvkqdfaIz4ZpQewmBv+cGF0kKqFWMskFBj7uoZb8YxISyTSANFbD8LpftOdNV8kHSD0IKEAQXR7PMmw6mh0unHvHut5Z93FVHtdvzQZ7cwoBEcVSYfV90Wvqg+NXfQ0LORu1sUFv/ptHGqYXqi1J3CofibIrM93Bg/VhU0+WjlFfyjsxDwWa7/WoFGTl7Ts/RDQJjDFrmNMWVYdpBPY0vAzyIdd1vIjh8AwlCQKhJKYVGFQuU6hu+CVDM7cY4Z3s2UfbDU5yA6F7eew9ZHMXCFympg1tjm7OoXNKxREZfAVJh0NMozwjf78D6LO1QG3hiVlcG4XjC31PlaJY1ijiOrfeT0xlkXWVf4izoaWcAx8uCw6822tnCXTmiyRGOM1KgvQ0e4HxVxYnLVmrmX1A3rvRgQuGBbrLw9Lny3Xmz3hMjTluULNxUMUJW/Avcu0BznFRY2rUs8kh31Ucz5q/EhdvVS2hdXh5pV3OOzP7H1R2b9+pnIZm0Mgth4+TsDsDLPkvE1eG9+HkN3Vlx9IU29jRow="
