language: python
sudo: required
cache:
  directories:
  - "$HOME/.cache/pip"
python:
- '3.6'
- '3.7'
env:
  global:
  - PYPI_USER=amn41
  - secure: "OWe6Fd/tXcCNvRBMJvFIXtDpnA0rQMFE/rLrzEZqmR9KOZs5dfEu3Bb7SW/22iIsAxSUjvGlqlcdp+QBPAw1XiD17aAJYvbCxh+c6xo264PyHOIhKzac23vmEzFr97LT3LKRIr1wULqGN05wMPGdzK7QK03aXfIRneBOphHM7fbT0Hl8zBTL7YwSuaA+Xic67fIFcd75Ynq8SGP1Gmoyu7NFfWRGxhL5+tPR+iuGkGfGf6nOBl0h9bfwU3moR9cVIe3mrcllcp5TonxfDtS8i7Mgs/jxCyNqWP1PufaLZVM/iFG9s25Yzpy478EH0rhLPRWAfXnTVov/5KOMrVSc1jrrO3eyxVXxubwAemgd4RTT6tihzZunAdFVQL0NTT78uPpqofJrvI0HAFt+0jJz4Ok+KFSqHjTPqSmndD1CtFh3hdIRydpV+Yp/ixC3c60gPTT+hydFtg3nARk+BPdUed0iF8j0AnPfDzW5QNKsYYFudm7FfjdOtCIu/tdKckfdh2mk+q4PcqJtgz97gc8b+X3l87bJFNmIWAIGMpKzK788N+EB18JR4gIOi6WqynUJaeq965lNIoDQtCxI/w7iRegE3UlRf/WZXUgL8jgN6w/EQXJDGZBkBi7W51AXuVYMvh7YK94j1IvXar6oNhYFqjsYW02vLgnG8Nwx3YR1Zr8="
before_install:
- pip install poetry~=1.0.3 # keep this in sync with the version in pyproject.toml and Dockerfile
install:
- poetry install
script:
- travis_wait py.test tests --cov rasa_sdk -v
after_success:
- poetry run coveralls
jobs:
  include:
  - stage: test
    name: Code Formatting
    python: 3.6
    script:
    - make lint
  - stage: test
    name: Type Check
    python: 3.6
    script:
    - make types
  - stage: deploy
    python: 3.6
    install: skip
    script: skip
    before_deploy:
    - poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD
    - poetry build
    deploy:
    - provider: script
      script: poetry publish
      on:
        branch: master
